services:
  postgres:
    image: postgres:15
    container_name: aimm-postgres
    env_file:
      - ./apps/indexer/.env.docker
    ports:
      - "5432:5432"
    # volumes:
    # - postgres_data:/var/lib/postgresql/data
  agent:
    build:
      context: ./apps/agent
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development
    env_file:
      - ./apps/agent/.env
    volumes:
      - ./apps/agent:/app
    restart: unless-stopped
    depends_on:
      - postgres

  indexer:
    build:
      context: ./apps/indexer
      dockerfile: Dockerfile
    ports:
      - "42069:42069" # Ponder default API port
    environment:
      - NODE_ENV=production
    env_file:
      - ./apps/indexer/.env.docker
    volumes:
      - ./apps/indexer:/app
      - /app/node_modules # Anonymous volume to avoid overwriting node_modules
    restart: unless-stopped
    depends_on:
      - postgres
# volumes:
# postgres_data:
