services:
  postgres:
    image: postgres:15
    container_name: aimm-postgres
    env_file:
      - ./apps/indexer/.env.docker
    ports:
      - "5432:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgres/init-aimm-db.sh:/docker-entrypoint-initdb.d/init-aimm-db.sh
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 30s # Add this - gives postgres 30s to start before checking health
  #agent:
  #  build:
  #    context: ./apps/aimm-agent
  #    dockerfile: Dockerfile
  #  ports:
  #    - "5002:5000"
  #  environment:
  #    - FLASK_ENV=development
  #  volumes:
  #    - ./apps/aimm-agent:/app
  #  restart: unless-stopped
  #  depends_on:
  #    - postgres

  indexer:
    build:
      context: .
      dockerfile: ./apps/indexer/Dockerfile
    # Expose directly for HTTP access, Caddy handles HTTPS
    ports:
      - "42069:42069"
    environment:
      - NODE_ENV=production
    env_file:
      - ./apps/indexer/.env.docker
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
