import { cookieStorage, createStorage } from 'wagmi';
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi';
import { mainnet, arbitrum, sepolia } from '@reown/appkit/networks';
import type { Chain } from 'viem';

// Reown Project ID (public)
export const projectId = '3d700ed0ed7056594f8c943b7deb1662';

// Define supported networks, explicitly typed as a non-empty array of Chains
export const networks: [Chain, ...Chain[]] = [mainnet, arbitrum, sepolia];

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({ storage: cookieStorage }),
  ssr: true,
  projectId,
  networks,
});

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig;
