query GetMarkets {
  markets {
    items {
      id
      externalId
      marketName
      subtitle
      optionAText
      optionBText
      platform
      status
      createdAt
      updatedAt
      optionACurrentExternalPrice
      optionBCurrentExternalPrice
      optionACurrentFairPrice
      optionBCurrentFairPrice
      lastExternalPriceUpdate
      lastFairPriceUpdate
      volume
    }
  }
}

query GetMarket($id: String!) {
  market(id: $id) {
    id
    externalId
    marketName
    subtitle
    optionAText
    optionBText
    platform
    status
    createdAt
    updatedAt
    optionACurrentExternalPrice
    optionBCurrentExternalPrice
    optionACurrentFairPrice
    optionBCurrentFairPrice
    lastExternalPriceUpdate
    lastFairPriceUpdate
    volume
  }
}
